// Jenkinsfile v1.13.8 — GS2.0
node('ec2-agent-01') {
    deleteDir()
    checkout scm
    def runner = load 'Katalon Studio/Jenkinsfile-runner.groovy'
    runner.run(
        katalon_dir:     'Katalon Studio/GS2.0',
        katalon_project: 'GS2.0.prj',
        katalon_suite:   'Test Suites/Headless-PROD'
    )
}
