// Jenkinsfile v1.13.8 — RESPONSE
node('ec2-agent-01') {
    deleteDir()
    checkout scm
    def runner = load 'Katalon Studio/Jenkinsfile-runner.groovy'
    runner.run(
        katalon_dir:     'Katalon Studio/RESPONSE',
        katalon_project: 'RESPONSE.prj',
        katalon_suite:   'Test Suites/Headless-PROD'
    )
}
